services:
  icm:
    container_name: internet-connectivity-monitor
    image: ghcr.io/roguedbear/icm:v2.1.2-roguedbear-1
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: host
    stop_grace_period: 0s
    restart: unless-stopped
    environment:
      TG_CHAT_ID:
      TG_BOT_TOKEN:
